### PR TITLE
fix: when an option field is object type and is missing from request …

### LINKED ISSUE #356: [BUG] oas tool 3.0 fail to treat optional field in schema as option.
## **Describe the bug**
When we have a schema that defines a field of object type as optional, and if in the request body we don't include that optional field, oas tool complains.
## **To Reproduce**
1.  the schema of object definition as the following:

```components:
  schemas:
    TestDocument:
      type: object
      required:
      - version
      - id
      properties:
        version:
          description: Schema version
          type: string
        id:
          description: Unique ID
          type: string
          example: 1234567
        owner:
          $ref: '#/components/schemas/Owner'
    Owner:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uri
        name:
          type: string
          minLength: 1
          maxLength: 256
```
3. The following is the configuration to initiate the api server

```const http = require('http');
const express = require("express");
const { initialize } = require('@oas-tools/core');


const serverPort = 8000;
const app = express();
app.use(express.json({limit: '50mb'}));
const config = {
    middleware: {
        validator: {
            strict: true,
            requestValidation: true,
            responseValidation: true,
        },
    }
}


initialize(app, config).then(() => {
    http.createServer(app).listen(serverPort, () => {
    console.log("\nApp running at http://localhost:" + serverPort);
    console.log("________________________________________________________________");
    if (config.middleware.swagger?.disable !== false) {
        console.log('API docs (Swagger UI) available on http://localhost:' + serverPort + '/docs');
        console.log("________________________________________________________________");
    }
    });
});
```
4.  Send the following in a request body
{
  "version": "v1",
  "id": "12"
}
## **Expected behavior**
This should pass the schema validation. 
Instead, the API sever return 404 with the following error
{
    "error": "RequestValidationError: Request body does not match the schema specified in the OAS Document:\n- Validation failed at #/properties/owner/required > must have required property 'id'"
}
## **Additional context**
this is for  oas-tool version "3.0.3

The problem is with parseBody function that it would set "owner" value  as {} .  it results in  the schema validation.  The "owner" should be omitted in this case.

### PR DESCRIPTION
**Pull request by cll023**
When an optional field is object type and is missing from the request body, the request body shall considered as valid

Refs: #356

### Initial checks

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you linked an issue to this pull request? (Create one if it does not exist)
* [x] Have you used [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format?

### [ISSUE TYPE] 
Bug

#### Description

When an optional field is object type and is missing from the request body,  the request failed scheme validation. 

#### Implementation details

When the optional field is object type and is missing from the request body,   instead of setting the fields as {} after parseBody,  set it as undefined.
Also added a unit test case

### CODE REVIEW

**Comment by alesancor1** [comment]
Hello @cll023, I've reviewed this PR andeverything looks fine. I've been fixing some other bugs and merging another PRs and there are some conflicts now in test files, could you please solve them? :)

**Comment by cll023** [comment]
HI @alesancor1 , I resolved the conflict in the test files, they are very minor change.  but now the test cases are not passing.  I am not sure what is the problem.  Please help.  Thanks

**Comment by alesancor1** [comment]
Don't worry I'll look at it asap :)

**Comment by cll023** [comment]
@alesancor1 Thank you so much .  I fixed the problem, now all are passing  :-)

**Review by alesancor1 — APPROVED** [review]

**Pull request merged**
